### PR TITLE
PR?

### PR DESCRIPTION
**Pull request by rwwagner90**
Just noticed you updated some stuff. Why no PR @jskeate?

### CODE REVIEW

**Comment by jskeate** [comment]
#3 -- then no update on that so I went rogue.

**Comment by rwwagner90** [comment]
Ahhhh, for some reason github never gives me notifications on repos that I own.

**Comment by rwwagner90** [comment]
@jskeate added you as a collaborator, so feel free to make whatever changes you need to. I trust you :smile:

**Comment by jskeate** [comment]
Cool! Thanks

/immediately trashes the place

**Comment by rwwagner90** [comment]
`git pull && cd ember-drop && git push --force` should do the trick :stuck_out_tongue_closed_eyes:

**Pull request merged**
